version: '3.4'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=auctionsuser
      - POSTGRES_PASSWORD=auctionsuserpw
      - POSTGRES_DB=auctions
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
       - 5432:5432