version: "3.4"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=auctionsuser
      - POSTGRES_PASSWORD=auctionsuserpw
      - POSTGRES_DB=auctions
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27018:27017"
    volumes:
      - /var/lib/mongodb/data
